name: Scheduled Ping
# This workflow is triggered at a scheduled interval of every 15 minutes
on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  pinger_job:
    name: A job to ping
    runs-on: ubuntu-latest
    env:
      URL: 'https://sc.scoldercreation.repl.co'
      METHOD: GET  # the method used to make the request. It is GET by default
    steps:
      - id: ping
        uses: sisodiya2421/pinger@master
